<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright 2025 Physikalisch-Technische Bundesanstalt

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are met:

  1. Redistributions of source code must retain the above copyright notice,
  this list of conditions and the following disclaimer.

  2. Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

  3. Neither the name of the copyright holder nor the names of its contributors
  may be used to endorse or promote products derived from this software without
  specific prior written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
  OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
  OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="2.2.0"
           targetNamespace="http://qudt.org/vocab/"
           elementFormDefault="qualified">
  <xs:annotation>
    <xs:documentation xml:lang="en">
      D-SI - Digital System of Units
      Copyright (c) 2018 - 2023 Physikalisch-Technische Bundesanstalt (PTB), all rights reserved.

      This XML Scheme Definition (XSD) is free software: you can redistribute it and/or modify
      it under the terms of the GNU Lesser General Public License as published by
      the Free Software Foundation, version 3 of the License.

      This XSD is distributed in the hope that it will be useful,
      but WITHOUT ANY WARRANTY; without even the implied warranty of
      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
      GNU Lesser General Public License for more details.

      You should have received a copy of the GNU Lesser General Public License
      along with this XSD. If not, see http://www.gnu.org/licenses.

      CONTACT: daniel.hutzschenreuter@ptb.de
      DEVELOPMENT: https://gitlab1.ptb.de/d-ptb/d-si/xsd-d-si
      D-SI XSD VERSION: 2.2.0
      RELEASE DATA: 2023-11-30
      DOI: 10.5281/zenodo.3366901
    </xs:documentation>
    <xs:documentation xml:lang="en">
      ACKNOWLEDGEMENT:
      This schema was developed to link QUDT type entities to the D-SI XML implementation.
      Please, visit qudt.org for information about the QUDT web ontology.
      To access the QUDT entries for quantity kinds from the XML, you can use the following PIDs:
      https://qudt.org/vocab/quantitykind/Length (web page)
      https://qudt.org/vocab/quantitykind/Length.ttl (machine-readable TURTLE data)
    </xs:documentation>
  </xs:annotation>
  <xs:simpleType name="quantitykind">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>
</xs:schema>
