<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright 2025 Physikalisch-Technische Bundesanstalt

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are met:

  1. Redistributions of source code must retain the above copyright notice,
  this list of conditions and the following disclaimer.

  2. Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

  3. Neither the name of the copyright holder nor the names of its contributors
  may be used to endorse or promote products derived from this software without
  specific prior written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
  OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
  OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <artifactId>oplayer-parent</artifactId>
    <groupId>de.ptb.common</groupId>
    <version>1.0-SNAPSHOT</version>
    <relativePath>../parent-pom/pom.xml</relativePath>
  </parent>

  <artifactId>gemimeg-backend-project</artifactId>
  <packaging>pom</packaging>
  <version>${revision}</version>

  <modules>
    <module>gemimeg-backend</module>
    <module>gemimeg-backend-api</module>
  </modules>

  <properties>
    <dcc-namespace-uri>https://ptb.de/dcc</dcc-namespace-uri>
    <byte-buddy.version>1.15.1</byte-buddy.version>
    <fop.version>2.10</fop.version>
  </properties>

  <!-- SCM settings -->
  <scm>
    <connection>scm:git:ssh://git@itgit.bs.ptb.de:op-layer/gemimeg-backend-project.git</connection>
    <!--suppress CheckTagEmptyBody -->
    <tag></tag>
    <developerConnection>${project.scm.connection}</developerConnection>
  </scm>

  <!-- module repositories -->
  <repositories>
    <repository>
      <id>gitlab-maven</id>
      <url>https://itgit.bs.ptb.de/api/v4/groups/451/-/packages/maven</url>
    </repository>
  </repositories>
  <distributionManagement>
    <repository>
      <id>gitlab-maven</id>
      <url>https://itgit.bs.ptb.de/api/v4/projects/1569/packages/maven</url>
    </repository>
    <snapshotRepository>
      <id>gitlab-maven</id>
      <url>https://itgit.bs.ptb.de/api/v4/projects/1569/packages/maven</url>
    </snapshotRepository>
  </distributionManagement>
  <pluginRepositories>
    <pluginRepository>
      <id>maven-central</id>
      <url>https://itgit.bs.ptb.de/api/v4/projects/1569/packages/maven</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </pluginRepository>
  </pluginRepositories>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
          <execution>
            <id>generate-code-coverage-report</id>
            <phase>test</phase>
            <goals>
              <goal>report</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>