server:
  port: 10001
  ssl:
    enabled: false
  forward-headers-strategy: FRAMEWORK
  error:
    include-message: always
spring:
  profiles:
    active: user-${USERNAME}
  application:
    name: gemimeg-backend
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    lazy-initialization: true
    allow-bean-definition-overriding: true
common:
  security:
    enabled: ${server.ssl.enabled}
  dcc:
    schema-url: '@dcc-schema-url@'
    namespace-uri: '@dcc-namespace-uri@'
